// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXJxCfSe-m3kqCQXkmIZGT5_R3hc_PnQ',
    appId: '1:95268240158:web:fcb0fad4370a26a0d5670f',
    messagingSenderId: '95268240158',
    projectId: 'crb-ecom',
    authDomain: 'crb-ecom.firebaseapp.com',
    storageBucket: 'crb-ecom.appspot.com',
    measurementId: 'G-HF797MHZQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Wo6cYcPmYlYU4M0BbGyLLDgqG1pP2OU',
    appId: '1:95268240158:android:96d4a6d14041b7b8d5670f',
    messagingSenderId: '95268240158',
    projectId: 'crb-ecom',
    storageBucket: 'crb-ecom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASt2eAPmRwRoa5MO07GL2_bEFopBJ52-M',
    appId: '1:95268240158:ios:7b7f4b041066abbed5670f',
    messagingSenderId: '95268240158',
    projectId: 'crb-ecom',
    storageBucket: 'crb-ecom.appspot.com',
    iosClientId: '95268240158-6fao48bu5vbj6esjs6osdqs5aoansuu4.apps.googleusercontent.com',
    iosBundleId: 'com.crb.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASt2eAPmRwRoa5MO07GL2_bEFopBJ52-M',
    appId: '1:95268240158:ios:7b7f4b041066abbed5670f',
    messagingSenderId: '95268240158',
    projectId: 'crb-ecom',
    storageBucket: 'crb-ecom.appspot.com',
    iosClientId: '95268240158-6fao48bu5vbj6esjs6osdqs5aoansuu4.apps.googleusercontent.com',
    iosBundleId: 'com.crb.ecom',
  );
}
